language: node_js
script:
  - ./_scripts/run-tests.sh
  - ./_scripts/build.sh
branches:
  except:
  - master
cache: bundler
node_js:
 - 4
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - rvm install 2.1
  - gem install bundler
  - bundle install --path vendor/bundle
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: Bc8sgN7Q2qSL349XIw0Loc/sT2+7M9i9eitmw6hR4r22fErVontMeD0KaXkCL0pgs1qy2N/MP0tSdKhZD2jlpyP1OicwetmoJc4XEeM3QUjagG8qfhWJOWNMq1WBdWwM4hc4bOwUVchVAPUceorMTscF5ZtejxxFSq1zwTFBmeg=
  - secure: cZzIlGtTm/yRXJOT3sB8XJI/lJwtxMReOnpBLik/+KW36/hwFkOoYaJa6aif6bLaAixcH/IlmZYE6bNjMQ7HtSLoaZLzmBXu39Qhj305LT78A/r4P9zt43JFhAYB9T+WjzT3qeX1k+YKdhC8CM9p0GPAT1LQ24co5/TbOjKzpGs=
deploy:
  provider: script
  script: "./_scripts/build.sh"
  on:
    branch: source
