# Basic Info
title: Savas Labs
email: info@savaslabs.com
description: >
  We craft elegant Drupal web systems that propel organizations.
# Base URL is used in the manner that is specified by this guide
# (http://jekyllrb.com/docs/github-pages/) which is to say, it's
# not used at all.
baseurl: ""
url: "http://savaslabs.com"
comment_server_url: "http://comments.savaslabs.com"
comment_server_enabled: 1

# Professional and social media links
twitter_username: savas_labs
github_username: savaslabs

# Languages and syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax-highlighter: rouge

# Include static pages.
include: ["_pages"]

# Blog
paginate: 9
paginate_path: "/blog/page:num/"

# For Travis CI and gulp
exclude: ["vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json",
          "hologram_config.yml"]

# Collections
collections:
  team:
    output: true
    permalink: /company/:path/
  team-former:
    output: false
  case-studies:
    output: true
    permalink: /work/:path/
  services:
    output: true
    permalink: /services/:path/

# Gems
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-picture-tag
  - jemoji
  - jekyll-twitter-plugin

# Picture element presets
picture:
  source: "assets/img"
  output: "assets/processed-img"
  markup: "picture"
  presets:
    team_square:
      attr:
        class: "image--team-square"
        itemprop: "image"
      ppi: [1, 2]
      source_400:
        media: "(min-width: 400px)"
        width: "334"
      source_default:
        width: "254"
    team_individual:
      attr:
        class: "image--team-individual"
        itemprop: "image"
      ppi: [1, 2]
      source_400:
        media: "(min-width: 400px)"
        width: "350"
      source_default:
        width: "288"
    team_square_small:
      attr:
        class: "image--team-square-small"
        itemprop: "image"
      ppi: [1, 2]
      source_default:
        width: "288"
    team_blog_tile:
      attr:
        class: "image--team-blog-tile"
        itemprop: "image"
      ppi: [1, 2]
      source_default:
        width: "60"
    case_study:
      attr:
        class: "image--case-study"
        itemprop: "image"
      ppi: [1, 2]
      source_1200:
        media: "(min-width: 1200px)"
        width: "860"
      source_860:
        media: "(min-width: 860px)"
        width: "592"
      source_640:
        media: "(min-width: 640px)"
        width: "860"
      source_400:
        media: "(min-width: 400px)"
        width: "640"
      source_default:
        width: "400"
    post_featured_image:
      attr:
        class: "image--post-featured-image"
        itemprop: "image"
      ppi: [1, 2]
      source_1120:
        media: "(min-width: 1120px)"
        height: "539"
        width: "959"
      source_860:
        media: "(min-width: 860px)"
        height: "419"
        width: "746"
      source_640:
        media: "(min-width: 640px)"
        height: "484"
        width: "860"
      source_400:
        media: "(min-width: 400px)"
        height: "360"
        width: "640"
      source_default:
        height: "225"
        width: "400"
